### ISSUE TITLE
APIクライアントの問題流し込み系を賢くする

### ISSUE THREAD

**Issue by uplus** [ictsc/ictsc-score-server#211]
## todo
* [x] ARぽいハッシュ操作
* [x] Shell風メソッド(ls cat pwd cd)
* [x] GETs系のキャッシュ
  * ensure
  * 一括処理時のフックで大量にリクエストを送るのを防ぐ
  *   nested requestsの時の挙動を気をつけないとバグる(countを保持すれば良いかも)
* [x] 1ファイルでグループ作成&問題登録
* [x] メソッドの自動定義
* [x] いろいろ自動化
* [x] ファイルパスを自動探索
* [x] 問題文内の画像読み込み(と自動アップロード)
* 引数
  * [x] login (default: admin)
  * [x] host (default: localhost:3000)
* [x] 1ファイルでteam,member,problem_group,problemを登録

## メソッドの自動定義
* リクエストメソッドの自動定義
  * [x] GETs (一括)
  * [x] POST
  * [x] PUT
  * [x] DELETE
*  一括投稿、編集系メソッドの自動定義
  * [x] POSTs
  * [x] PUTs

## いろいろ自動化

* 外部ファイルから読み込み
  * [x] Problem#text
  * [x] Problem#secret_text
* [x] creator_id
* order  並び順で自動で振る(index * 100)
  * [x] problem
  * [x] problem_group
* problem_must_solve_before_id
  * [x] title指定
  * [x] 一括投稿時の順序
* [x] problem_group_ids
  * problem_groupに_problemsをもたせればよさそう
  * after系フックがあると良いかも
  * グループPOST後にPOST listする
* Member
  * [x] _role: :admin  で role_id: 2にする
  * [x] name  省略されたらloginを使う
