### ISSUE TITLE
テストが少ない

### ISSUE THREAD

**Issue by kyontan** [ictsc/ictsc-score-server#67]
# Why
- このアプリケーションの規模が小さい / そこまで複雑でないという認識をしていた
  - 実際にはそこそこエンドポイントがある
  - ドメインロジックが複雑なので、ひとつのエンドポイントに対しても考慮すべきことが多い
- そもそもドキュメントが不足しており、 @kyontan 以外が全くコードの挙動を理解できていない
  - 困る (引き継げない)
  - エンドポイントに対するリクエスト / レスポンス をテストケースとして用意することで、ドキュメンテーションの役割も兼ねたい
    - ドメインや動かし方に関するドキュメントは #65

# Tasks:

- [x] 必要な Factory を定義する
- [x] 必要な spec_helper 等を準備する
- [x] テストを書く
  - [x] `/api/answers`
  - [x] `/api/attachments`
  - [x] `/api/:commentables/:commentable_id/comments`
  - [x] `/api/contests`
  - [x] `/api/issues`
  - [x] `/api/members`
  - [x] `/api/notices`
  - [ ] ~`/api/notifications`~
  - [x] `/api/problems`
  - [x] `/api/problem_groups`
  - [x] `/api/scores`
  - [x] `/api/scoreboard`
  - [x] `/api/teams`

**Comment by kyontan** [comment]
テストを書き始めました

**Comment by kyontan** [comment]
通知については今回改めて実装を見直しているのでスキップします。
